Feature/a04 exist in directory rule
VitDeck/VitDeck-for-vket pull request #34
Opened 2020-01-13 11:47 UTC by sktkkoo

[A04]配布物以外の全てのオブジェクト参照が入稿フォルダ内に存在することを検証するルールを追加しました。テストコード用のシーンに配布物を含めることはしていませんが、配布物が検証対象から除外されることは一応確認済みです。

2020-01-13 13:54 UTC, sokuhatiku requested changes
こちらの環境でテスト中に上手く検出されず悩んでいたのですが、どうやら入稿者IDのフォルダと前方が一致するフォルダに入っているアセットを上手く検出できないようです……
例えば入稿フォルダが `Assets/Sokuhatiku` のとき、 `Assets/Sokuhatiku_Sub` というフォルダに入れているアセットがフォルダ外と認識してくれません

2020-01-13 16:17 UTC, sktkkoo commented
ご指摘ありがとうございます。修正しました！

2020-01-13 17:11 UTC, sokuhatiku commented
![image](https://user-images.githubusercontent.com/7193342/72276359-133b1700-3673-11ea-94e3-40f7e2946740.png)
今度は入稿フォルダ直下に配置されたフォルダが誤検出されるようです……。

2020-01-14 00:47 UTC, sktkkoo commented
遅くなって申し訳ないです。修正しました。

2020-01-14 14:06 UTC, sokuhatiku approved these changes
直っているようです。ありがとうございます！

2020-01-14 14:06 UTC, merged